controller:
  allowSnippetAnnotations: true
  admissionWebhooks:
    enabled: false
  config:
    use-forwarded-headers: "true"
    use-proxy-protocol: "true"
  replicaCount: 3
  service:
    externalTrafficPolicy: Local
    annotations:
      external-dns.alpha.kubernetes.io/hostname: ${app_hostname}
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: ${acm_certificate_arn}
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
